### ISSUE TITLE
Daily Antigen Testing

### ISSUE THREAD

**Issue by fantasai** [w3c/TPAC2022-Health-rules#6]
From https://github.com/w3c/AB-memberonly/issues/137 and https://lists.w3.org/Archives/Member/w3c-ac-forum/2022AprJun/0281.html and the recent AB discussions about requiring daily testing, here is the specific proposal:

- Include at least 1 antigen test per registered day in the TPAC registration welcome package. (This may require adjusting the cost of the tickets to absorb the cost, or soliciting a specific Sponsorship for tests.)
- Include in the health rules that each person will be required to take such a test on the morning of each day, before participating. Indicate that assistance will be available if needed. Require that participants not attend in person if they test positive, for that day and all subsequent days.
- Include on the TPAC badge design slots for COVID test results each day, to be filled in with a sticker after testing negative that morning. (This will help remind people that they need to run the test. We can have [fun stickers](https://www.amazon.com/gp/product/B0006NNJ04/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1) to make this fun.)
- Add the following checkbox to the TPAC registration form, to ensure every participant has understood the requirement and agrees to comply:
   - [ ] I agree to take a COVID antigen test every morning of the event, to accurately report those results to the event staff, and to isolate and attend only virtually on any day that test is positive as well as all subsequent days.

**Comment by svgeesus** [comment]
Stickers on badges is a nice idea and might increase compliance.

Did the checkbox get added to the registration form?

**Comment by fantasai** [comment]
> Stickers on badges is a nice idea and might increase compliance.

I would be happy to sponsor the stickers, fwiw! I can offer sparkly rainbow smiley faces, sparkly rainbow stars, or sparkly red hearts, and I can volunteer to both buy them and cut them into strips as long as the Events Team is willing to put appropriate slots on the badges.

> Did the checkbox get added to the registration form?

Yes, but with a lot more words!

**Comment by fantasai** [comment]
Fun sticker options:
- [rainbow small sparkly stars](https://www.trendenterprises.com/products/t46910)
- [rainbow large sparkly stars](https://www.trendenterprises.com/products/t46306)
- [rainbow small sparkly smiley faces](https://www.trendenterprises.com/products/t46909)
- [rainbow large sparkly smiley faces](https://www.trendenterprises.com/products/t46305)
- [red small sparkly hearts](https://www.amazon.com/enterprises-Sparkle-Hearts-superShapes-Stickers-Sparkle/dp/B00E9HSTQM/)

**Comment by frivoal** [comment]
I agree that some active means to show that participants did indeed take a test that day is highly desirable. If we're just telling people to take a test and leaving it at that, someone who shows up to the meeting might have taken a test, or they might have forgotten to take the test, or they might have misunderstood the rule and failed to realize that taking a test was required.

If some active step is needed to show that you took the test, that rules out the "forgot" or the "didn't understand" cases.

Stickers (of a different color or different symbol every day) is a very easy, very low cost means to achieve that.

In case there's any doubt that people might misunderstand:
* Many TPAC participants aren't native or fluent English speakers. It is very easy to miss some tidbit of information in the firehose of messenging that TPAC is. Or to misunderstand some sentence when you didn't realize it was particularly important to pay attention.
* The [TPAC Health rules](https://www.w3.org/2022/09/TPAC/health.html#on-site) page is around 4 A4 pages long if you print it. That's a large amount of text, highly at risk of being skimmed rather than read, parts of which could easily be forgotten.
* I'm just back from an event where the rules were very succinct (length: 16% of the TPAC rules word-count), and very explicit “Participants must self-test daily in the morning before each meeting day“. Yet a participant did not take daily tests, as they had assumed it was just a suggestion of useful behavior rather than a rule of the meeting. This was not willful non-compliance, as the participant had no issue admitting it, nor with taking a test once aware.

Asking people to put "I tested today" stickers on their badges has negligible cost, and can trivially provide an opportunity to remind / explain the testing rule to participants who would have accidentally failed to follow it.

**Comment by frivoal** [comment]
Addendum: I did not realize before, but TPAC is not only going to be attended by W3C members, but also seems (for some sessions) to be open to the public: See https://www.w3.org/2022/09/meetup/ for example.

I think that further raises the importance of active signaling of having taken a test. Relying on trust within a closed (even if large) community is one thing. Relying on trust for the general public doesn't make very much sense to me.

**Comment by alexandralacourba** [comment]
See https://github.com/w3c/TPAC2022-Health-rules/issues/18

**Comment by alexandralacourba** [comment]
As commented in a separate thread, we will not ask self attestation not enforce stickers to check if people do daily tests. However, a summary of the health rules will be distributed together with the badges and the tests. People will be also orally reminded to take daily tests when the register.
A reminder note will also been sent to all attendees before the meeting.
Signs reminding the health rules will be posted in rooms and common spaces.

**Comment by frivoal** [comment]
> As commented in a separate thread, we will not ask self attestation not enforce stickers to check if people do daily tests

I understand that this is the policy, but I do not understand why. As I said in https://github.com/w3c/TPAC2022-Health-rules/issues/6#issuecomment-1221510575, I strongly believe it would make a meaningful difference for next to zero cost.

**Comment by alexandralacourba** [comment]
As already stated in a separate thread, this includes displaying publicly a health status. Some attendees may feel uncomfortable with that. We can not enforce this, and on a voluntary basis, this does not give enough guarantee. Among other things, the health rules have been set up on the level of acceptance. It needs to be accepted and followed by attendees. Also, if the rules set does not give the level of guarantee we need to reach, we should not do it. But it is important that we do everything we can so that people remember to test daily. We are planning this.

**Comment by frivoal** [comment]
> this includes displaying publicly a health status

The rule is that a test must be taken before attending. Therefore, coming to the venue is also displaying publicly a health status.

The only difference is that an active display of a sticker means "I tested negative", while just attending means "I either tested negative or failed to follow the rule".

**Comment by alexandralacourba** [comment]
You are not clearly notified to the whole attendance that you tested positive. This difference is important for some attendees. We need to respect that. And as I mentioned, the fact to have stickers on a voluntary basis does not bring more the necessary guarantees and more guarantees to what we set up already.

**Comment by frivoal** [comment]
I am not asking to notify the whole attendance when you test positive. The stickers would be "tested negative today" stickers. If you test positive, you simply don't show up. Sticker or not, you need to do that anyway. And that does not involve broadcasting your condition.

Also the request isn't that the stickers would be optional, but mandatory. This enables the team and chairs, if they notice someone without a sticker, to remind them that they're supposed to take a test, and ask them to go do it before returning to the venue. No equivalent is possible without stickers (or some similar active notification system).

**Comment by alexandralacourba** [comment]
As you already mentioned and for the reasons already mentioned below, we will not go for the stickers options. We'll insist on reminding people so that they do not forget.
Thank you for your understanding

**Comment by koalie** [comment]
I concur with @alexandralacourba 
I do not concur with the notion that stickers might increase compliance. My main issue is that stickers would be a statement of mistrust of the mandate to show up on a given day only if you’ve tested negative.

I expect no interference with the planned organizational team's implementation of the health rules, and I think the issue ought to be closed.

**Comment by cwilso** [comment]
I'm sorry if this somehow is construed as a statement of mistrust.  From experience at our recent AB meeting, with a MUCH smaller sample set (8), we STILL had misunderstanding about the testing requirement, that a positive-compliance statement probably would have avoided.

I'm not sure what is intended by "I expect no interference"?

**Comment by astearns** [comment]
> We'll insist on reminding people so that they do not forget.

@alexandralacourba can you go into more detail about what kind of reminders you plan to make? So far I see a reminder at registration mentioned, a note sent out beforehand, and signage.

I hope that the note sent out beforehand will be short and focused on this one requirement. Please do not bury it in a list of other things.

Similarly, I think the entrances to the venue will need large, clear signs about this daily requirement, perhaps even with staff people at chokepoints verbally reminding people.

Given the AB/CSS experience, I expect quite a lot of TPAC attendees to not understand the requirement, and several who do understand the requirement to forget on one morning or another. If we are not going to have some sort of sticker-like ceremony that each participant can use to remind themselves, the staff will need to put in a lot of effort to protect everyone by doing those reminders for everyone.

**Comment by alexandralacourba** [comment]
- We will give flyers together with the badge reminding people about the main health rules: https://www.w3.org/2022/09/TPAC/signage/mask-required-02.pdf
- On the badge, we wrote: remember to test daily and wear a mask
- We will have foam boards at the registration desk stating: stating that attendees are required to test daily and that covid tests are available
- We will put health rules reminders (link above) in each  meetings rooms, and common space
- We will also ask the chairs to remind the main rules (link above) at the beginning of each session.

I intend to send an email,on this, indeed.  Stating that we require people to test daily and also inform them that we open the registration on Sunday 16:00 to 18:00 so that people can grab their badge *and" their test for Monday morning.

**Comment by astearns** [comment]
Thanks for the details. Perhaps the daily tests themselves can be set out prominently at the registration desk each day? A pile of “swag” is probably more attention-grabbing than any sign.

**Comment by alexandralacourba** [comment]
yes, we will put the daily tests prominently on the registration desk (maybe not at once because we have thousands of them) ;)
